<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nattable" nsURI="http://eclipse.org/rcptt/tesla/nattable"
    nsPrefix="org.eclipse.rcptt.tesla.nattable">
  <eClassifiers xsi:type="ecore:EClass" name="NatTableMouseEvent" eSuperTypes="../../org.eclipse.rcptt.tesla.core/models/protocol.ecore#//ElementCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="button" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateMask" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//NatTableMouseEventKind"
        defaultValueLiteral="DOWN"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnHeader" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowHeader" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NatTableMouseEventKind">
    <eLiterals name="DOWN" literal="DOWN"/>
    <eLiterals name="UP" value="1"/>
    <eLiterals name="CLICK" value="2" literal="CLICK"/>
  </eClassifiers>
</ecore:EPackage>
